/* eslint-disable @typescript-eslint/no-unsafe-assignment */
/* eslint-disable @typescript-eslint/no-unsafe-member-access */

import axios from "axios";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import { CodeItemDisplay } from "~/components/CodeItemDisplay";
import { Footer } from "~/components/Footer";
import { type Code } from "~/interfaces";

export default function Dashboard() {
  const [codes, setCodes] = useState<Code[]>();

  const getData = async () => {
    const url = process.env.NEXT_PUBLIC_SERVER_URL;
    if (!url) return;
    const res = await axios.get(url);
    const data = res.data;
    if (!data?.codes) return;
    setCodes(data.codes as Code[]);
  };

  useEffect(() => {
    void getData();
  }, []);

  return (
    <>
      <Head>
        <title>Fornecedor7 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center gap-4 bg-gray-100">
        <Image
          src={"/images/logo.png"}
          alt="logo"
          className=""
          height={300}
          width={300}
        />
        <div className="mx-auto mb-4 max-w-[80vw] border-b border-blue px-8 pb-2 text-center font-semibold text-gray-400"></div>

        <div className="my-12 flex flex-col gap-4">
          {codes
            ?.sort((a, b) => a.value - b.value)
            .map((code, index) => (
              <CodeItemDisplay key={`code-item-display-${index}`} code={code} />
            ))}
        </div>

        <Footer />
      </main>
    </>
  );
}
